# Generated by Django 4.1.7 on 2023-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pic',
            field=models.FileField(default='defualt.png', upload_to='seller_profile'),
        ),
    ]
