# Generated by Django 4.1.7 on 2023-02-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
