# Generated by Django 4.1.7 on 2023-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_alter_buyer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pic',
            field=models.FileField(default='default.png', upload_to='buyer_profile'),
        ),
    ]
